from __future__ import annotations

import os
import subprocess
from pathlib import Path
from typing import Any, Dict


# ============================================================
# EXISTING FALL-DETECTION PROJECT
# ============================================================

FALL_DETECTION_PROJECT = Path(
    r"C:\Users\adity\OneDrive\Desktop\multimodal_fall_detection"
)

FALL_DETECTION_SCRIPT = (
    FALL_DETECTION_PROJECT / "final_predict.py"
)

FALL_DETECTION_PYTHON = (
    FALL_DETECTION_PROJECT
    / "venv"
    / "Scripts"
    / "python.exe"
)


# ============================================================
# RUN FALL DETECTOR
# ============================================================

def run_fall_detection() -> Dict[str, Any]:
    """
    Run the existing multimodal fall detector and extract
    its real prediction probabilities.

    The current prototype uses the existing
    Subject 1 / Activity 1 / Trial 1 demonstration pipeline.
    """

    # --------------------------------------------------------
    # Check project
    # --------------------------------------------------------

    if not FALL_DETECTION_PROJECT.exists():
        raise FileNotFoundError(
            "Fall detection project not found:\n"
            f"{FALL_DETECTION_PROJECT}"
        )

    # --------------------------------------------------------
    # Check prediction script
    # --------------------------------------------------------

    if not FALL_DETECTION_SCRIPT.exists():
        raise FileNotFoundError(
            "Fall detection script not found:\n"
            f"{FALL_DETECTION_SCRIPT}"
        )

    # --------------------------------------------------------
    # Check Python environment
    # --------------------------------------------------------

    if not FALL_DETECTION_PYTHON.exists():
        raise FileNotFoundError(
            "Fall detection Python environment not found:\n"
            f"{FALL_DETECTION_PYTHON}"
        )

    print(
        "\nRunning multimodal fall detector..."
    )

    # --------------------------------------------------------
    # Child-process environment
    # --------------------------------------------------------

    environment = os.environ.copy()

    # Force UTF-8 so the Unicode symbols in final_predict.py
    # do not crash on Windows.
    environment["PYTHONIOENCODING"] = "utf-8"
    environment["PYTHONUTF8"] = "1"

    # IMPORTANT:
    # Run Matplotlib without an interactive window.
    #
    # final_predict.py ends with plt.show(), which would otherwise
    # keep the subprocess alive indefinitely when called by FastAPI.
    #
    # The dashboard is still generated by final_predict.py and
    # saved as fall_detection_dashboard.png.
    environment["MPLBACKEND"] = "Agg"

    # --------------------------------------------------------
    # Run existing fall detector
    # --------------------------------------------------------

    result = subprocess.run(
        [
            str(FALL_DETECTION_PYTHON),
            str(FALL_DETECTION_SCRIPT),
        ],
        cwd=str(FALL_DETECTION_PROJECT),
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
        env=environment,
        timeout=180,
    )

    # --------------------------------------------------------
    # Check execution result
    # --------------------------------------------------------

    if result.returncode != 0:
        raise RuntimeError(
            "Fall detection failed:\n"
            + result.stderr
        )

    output = result.stdout

    # --------------------------------------------------------
    # Extract real model probabilities
    # --------------------------------------------------------

    wearable = _extract_percentage(
        output,
        "WEARABLE"
    )

    environment_probability = _extract_percentage(
        output,
        "ENVIRONMENT"
    )

    vision = _extract_percentage(
        output,
        "VISION"
    )

    fusion = _extract_percentage(
        output,
        "FINAL FUSION"
    )

    # --------------------------------------------------------
    # Extract final decision
    # --------------------------------------------------------

    fall_detected = (
        "RESULT            : FALL DETECTED"
        in output
    )

    # --------------------------------------------------------
    # Build structured result
    # --------------------------------------------------------

    detection_result = {
        "wearable_probability": wearable,
        "environment_probability": environment_probability,
        "vision_probability": vision,
        "final_score": fusion,
        "fall_detected": fall_detected,
    }

    # --------------------------------------------------------
    # Display integration result
    # --------------------------------------------------------

    print(
        "\nFall detection result:"
    )

    print(
        f"  Wearable     : {wearable:.2%}"
    )

    print(
        f"  Environment  : {environment_probability:.2%}"
    )

    print(
        f"  Vision       : {vision:.2%}"
    )

    print(
        f"  Fusion       : {fusion:.2%}"
    )

    print(
        f"  Fall detected: {fall_detected}"
    )

    return detection_result


# ============================================================
# EXTRACT PERCENTAGE
# ============================================================

def _extract_percentage(
    output: str,
    label: str,
) -> float:
    """
    Extract a percentage from final_predict.py output.

    Example:

        FINAL FUSION   : 97.65% FALL

    Returns:

        0.9765
    """

    for line in output.splitlines():

        if label not in line:
            continue

        if ":" not in line:
            continue

        try:

            value_part = line.split(
                ":",
                1
            )[1].strip()

            percentage_text = (
                value_part
                .split("%", 1)[0]
                .strip()
            )

            return float(
                percentage_text
            ) / 100.0

        except ValueError:
            continue

    raise RuntimeError(
        f"Could not extract {label} probability "
        "from fall detector output."
    )